# Use the official Node.js 14 image as the base image
FROM node:18-alpine

RUN npm install -g pnpm
RUN npm install -g next

# Set the working directory to /app
WORKDIR /app


# Set the command to run when the container starts
CMD ["pnpm", "start"]