# Use the official Node.js 14 image as the base image
FROM node:18-alpine

RUN npm install -g pnpm
RUN npm install -g next

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./
COPY pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --prod

# Copy the rest of the app to the container
COPY . .

# Build the app
RUN pnpm run build


# Set the command to run when the container starts
CMD ["pnpm", "start"]