version: "3.9"

services:
  sendgrid:
    image: ghashange/sendgrid-mock:1.7.2
    ports:
      - "7007:3000"
    environment:
      - API_KEY=SG.mock

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: cypress
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: dockerfile.api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: cypress
    depends_on:
      - sendgrid
